import { IBranch } from 'src/types/Branches.d';

export interface IBranchState {
  currentBranchId: string,
  branches: IBranch[];
}

function state(): IBranchState {
  return {
    currentBranchId: '',
    branches: [
      {
        id: 'branch-1',
        lastMessageAuthor: 'Peter',
        subject: 'Holiday',
        count: 4,
        date: 1625215179589,
        labels: ['Freelance'],
        starred: true,
        folder: 'inbox',
        read: true,
      },
      {
        id: 'branch-2',
        lastMessageAuthor: 'me',
        subject: 'Sale car',
        count: 3,
        date: 1624815179589,
        labels: ['Friends'],
        starred: false,
        folder: 'inbox',
        read: true,
      },
      {
        id: 'branch-3',
        lastMessageAuthor: 'Gleb',
        subject: 'User-friendly value-added application',
        count: 5,
        date: 1624515179589,
        labels: [],
        starred: true,
        folder: 'inbox',
        read: true,
      },
      {
        id: 'branch-4',
        lastMessageAuthor: 'John',
        subject: 'Focused impactful open system',
        count: 2,
        date: 1624015179589,
        labels: ['Social'],
        starred: false,
        folder: 'inbox',
        read: true,
      },
      {
        id: 'branch-5',
        lastMessageAuthor: 'me',
        subject: 'Profound systemic alliance',
        count: 1,
        date: 1623815179589,
        labels: [],
        starred: false,
        folder: 'inbox',
        read: true,
      },
      {
        id: 'branch-6',
        lastMessageAuthor: 'Alex',
        subject: 'Organized value-added model',
        count: 4,
        date: 1623615179589,
        labels: ['Social', 'Support'],
        starred: false,
        folder: 'trash',
        read: true,
      },
      {
        id: 'branch-7',
        lastMessageAuthor: 'me',
        subject: 'Quality-focused methodical flexibility',
        count: 3,
        date: 1623315179589,
        labels: [],
        starred: false,
        folder: 'trash',
        read: true,
      },
      {
        id: 'branch-8',
        lastMessageAuthor: 'me',
        subject: 'Company Report',
        count: 2,
        date: 1623015179589,
        labels: ['Support'],
        starred: false,
        folder: 'trash',
        read: true,
      },
      {
        id: 'branch-9',
        lastMessageAuthor: 'Kim',
        subject: 'Theme Update',
        count: 4,
        date: 1622815179589,
        labels: [],
        starred: true,
        folder: 'trash',
        read: true,
      },
      {
        id: 'branch-10',
        lastMessageAuthor: 'Billy',
        subject: 'Wedding',
        count: 2,
        date: 1622415179589,
        labels: ['Friends', 'Social'],
        starred: true,
        folder: 'trash',
        read: true,
      },
    ],
  };
}

export default state;
